# 데이터 분석 python 라이브러리

### 1. Matplotlib
- 지금까지 배움
- Matplotlib -> (확장) -> seaborn

### 2. Numpy
- Numerical Python 의 줄임말
- 행렬, 수치, 계산 등 데이터를 다루기 쉽게 도와줌

### 3. Pandas
- Panel Datas 의 줄임말
- 테이블 형태의 데이터를 다루기 쉽게 도와주는 라이브러리
- csv, html, sql 등 다양한 데이터를 읽을 수 있음

## Numpy 란?

- numpy는 수치 데이터를 다루기 위한 라이브러리
    - (다차원 배열 구조인 ndarray 를 이용하여) 행렬/백터 및 수치 연산을 빠르게 하는 것이 핵심

- list 와 numpy array 의 연산 속도 차이는 30~40배까지 나기도 함
    - C언어로 구현된 파이썬 라이브러리라서 겁나 빠름
    
- **데이터의 크기가 커질수록 numpy 필수!**

## 차원

- **중첩리스트** : 리스트 안의 리스트

- **차원** : 중첩된 정도를 구분하기 위한 단위

- 일반적인 리스트는 중첩 데이터를 처리하는게 느리고 복잡함 -> **numpy 라이브러리 사용!**

### - 1차원 배열 생성

- np.array() 는 리스트, 튜플, 배열로 부터 ndarray 생성

In [1]:
# numpy 라이브러리 import
import numpy as np

In [2]:
# 1차원 배열 생성하기
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


### - 2차원 배열 생성

In [3]:
# 2차원 배열 생성하기
b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [4]:
# 변수를 사용하여 2차원 배열 생성
i_list = [[1,2,3],[4,5,6]]
b = np.array(i_list)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


### - 배열의 차원 및 크기 확인

In [5]:
# 배열의 차원 및 크기 확인
# ndim 및 shape 속성으로 출력하기
print(b.ndim)
print(b.shape)

2
(2, 3)


In [6]:
print(a.ndim)
print(a.shape)

1
(5,)


## ndarray 초기화 방법
- list 를 이용하여 ndarray 생성


- 그 외


**np.zeros((a,b))** : 모든 값이 0인 a x b 크기의 배열 생성

numpy.zeros(shape, dtype=float, order='C')

In [10]:
# 모든 값이 0 인 2x3 배열 생성
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

**np.ones((a,b))** : 모든 값이 1인 a x b 크기의 배열 생성

numpy.zeros(shape, dtype=None, order='C')

In [12]:
# 모든 값이 1 인 2x3 배열 생성
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

**np.full((a,b),c)** : 모든 값이 c인 a x b 배열 생성

numpy.full(shape, fill_value, dtype=None, order='C')

In [19]:
# 모든 값이 5인 2x3 배열 생성
a = np.full((2,3),5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [20]:
# dtype 설정 : np.int8
b = np.full((2,3),5, dtype=np.int8)
b

array([[5, 5, 5],
       [5, 5, 5]], dtype=int8)

In [21]:
# dtype 설정 : np.float64
c = np.full((2,3),5, dtype=np.float64)
c

array([[5., 5., 5.],
       [5., 5., 5.]])

In [23]:
# 모든 값이 1.5인 2x3 배열 생성
d = np.full((2,3),1.5)
d

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

**np.eye(a)** : 대각선 값은 1이고 나머지는 0인 a x a 크기의 2차원 배열 생성

**np.eye(a,b)** : a x b 크기의 2차원 배열 생성

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

In [24]:
# 대각선 값은 1이고 나머지는 0인 3x3 크기의 2차원 배열 생성
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# 대각선 값은 1이고 나머지는 0인 3x4 크기의 2차원 배열 생성
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**np.random.randn(a,b)** : 임의의 값으로 채워진 axb 크기의 배열 생성

In [26]:
# 임의의 값으로 채워진 2x3 배열
np.random.randn(2,3)

array([[ 2.2802272 , -1.59627189, -0.69372046],
       [-0.80970777,  1.7480441 , -0.16946145]])

## 슬라이싱(Slicing)

- ndarray 를 통해 만든 다차원 배열은 list 처럼 슬라이스 기능 지원
    - 슬라이스 기능을 사용하여 여러개의 원소에 접근 할 수 있음
    
- 각 차원별로 슬라이스 범위 지정

In [27]:
a = np.array([1,2,3])
b = a[0:2]
b

array([1, 2])

In [28]:
a = np.array([[1,2,3],[4,5,6]])
b = a[0:2,0:2]
b

array([[1, 2],
       [4, 5]])

## Numpy 연산

- ndarray 로 만든 자료형은 자유롭게 사칙연산 가능
    - 배열간 연산을 손쉽게 수행할 수 있음

1) +, -, *, / 연산자 사용

2) add(), substract(), multiply(), divide() 함수 사용

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [30]:
# 동일한 인덱스에 위치한 요소끼리 덧셈
# c = np.add(a,b)와 동일
c = a+ b
c

array([5, 7, 9])

In [31]:
# 동일한 인덱스에 위치한 요소끼리 뺄셈
# c = np.substract(a,b)와 동일
c = a - b
c

array([-3, -3, -3])

In [32]:
# 동일한 인덱스에 위치한 요소끼리 곱셈
# c = np.n=multiply(a,b)와 동일
c = a * b
c

array([ 4, 10, 18])

In [33]:
# 동일한 인덱스에 위치한 요소끼리 나눗셈
# c = np.divide(a,b)와 동일
c = a / b
c

array([0.25, 0.4 , 0.5 ])

## Numpy array 와 list 차이

### 차이 1) 사칙연산
- Numpy array 는 Numpy array 끼리 사칙연산이 가능하지만 Python list는 덧셈만 가능
    - numpy array + numpy array : 같은 인덱스에 있는 값끼리 더해짐
    - list + list : 두 리스트가 한 리스트로 합쳐짐(이어짐)

In [35]:
# numpy array 의 덧셈
np_a = np.array([1,2,3])
np_b = np.array([3,4,5])
a+b

array([5, 7, 9])

In [36]:
# python list의 덧셈
a = [1,2,3]
b = [3,4,5]
a+b

[1, 2, 3, 3, 4, 5]

### 차이 2) 곱셈
- numpy array * 숫자 : 요소 각각에 연산 적용
- list : list의 요소 반복

In [38]:
# numpy array * 3
np_a = np.array([1,2,3])
np_a*3

array([3, 6, 9])

In [39]:
# python list * 3
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

### 차이 3) 성능차이

- Python list 에 비해 문법이 간단하고 성능이 뛰어남
    - 예를 들어 1 억 개의 요소가 있는 기본 python list 에 곱하기 2 를 하려면
        - 반복문을 1 억 번 돌려야 함
        ``` for i in range(1억):i*2```
    - numpy array 는 그냥 * 2 만 붙여주면 됨

**성능 차이가 나는 이유 ?**
- 값들이 저장되는 방식에 차이
    - python list 는 다양한 자료형을 저장 가능
    - numpy array 는 같은 자료형만 저장 가능

## 결론
**python list** : 값을 추가하고 제거할 때 사용

**numpy list** : 수치 계산이 많고 복잡할 때 혹은 행렬 같은 다차원 배열을 쓸 때 사용